### ISSUE TITLE
firebase/angularfire reference has wrong casing

### ISSUE THREAD

**Issue by hindsholm** [Microsoft/ngconf2015demo#10]
Compilation fails on Linux (Ubuntu 14.10) because 

`import {AngularFire, FirebaseArray} from 'firebase/Angularfire';`

does not match the file `firebase/angularfire.d.ts`.
The reference should be with a lowercase 'a' instead 'A'.

I am not able to make a pull request right now, sorry.

**Comment by danquirk** [comment]
Should be fixed by #11 now.
