### ISSUE TITLE
Where should tsconfig.conf go?

### ISSUE THREAD

**Issue by oivvio** [Microsoft/ngconf2015demo#12]
I'm trying out the Sublime plugin that comes with this repository and it's working great.

One thing that I can't get working right though is imports. In the supplied examples everything works great but when I try to edit a .ts file in an other folder I get `Cannot compile external modules unless the '--module' flag is provided` on any import statement.

Digging around in your repository I find tsconfig.conf that seems be responsible for getting the compiler to the right thing for your example. 

```
{
    "compilerOptions": {
        "module":"AMD"
    },
    "files": [
       "todo.ts"
    ]
}
```

So I tried copying this to the my own repository, replacing `todo.js`with my own file, and restarting Sublime. I tried a bunch of different locations relative to the source path, and relative to my `tsserver.js`. So far I've haven't had any luck. Any pointer would be much appreciated.

**Comment by vladima** [comment]
Version of Sublime plugin that was snapped for ngconf demo does not yet support tsconfig file. Adding it something that we have on the list.
