### ISSUE TITLE
Demo application failure

### ISSUE THREAD

**Issue by MarkStega** [Microsoft/ngconf2015demo#13]
I cloned the ngconf demo today; The update to VS2013 worked as I can peek/goto definitions. I ran the transpile using node, it appeared to work as I have a todo.js file. When I try to browse to index.html I see the GET of index.html in http-server console output followed by 30+ GETs of various bits of Angular, finishing with shim_css.js;

The only thing displayed in the browser is "Loading..."

Windows 8.1 64 bit, IE 11

**Comment by sophiajt** [comment]
It may be an IE 11 incompatibility in the demo. It's copied from David East's Angular 2 example, and I'm not sure if IE was tested.  Do you get the same thing when using Chrome?

**Comment by MarkStega** [comment]
Same results on Chrome & Firefox

**Comment by sophiajt** [comment]
This seems to be related to a fix I did for case-sensitive file systems.  Reverting my fix, which should help in Windows/Mac and looking into a better one.

**Comment by vladima** [comment]
if you open DevTools in Chrome and enable 'pause on exceptions' do you see any exceptions during the loading of the page?

**Comment by MarkStega** [comment]
GET http://localhost:8080/ng/firebase/angularfire.js 404 (Not Found)
zone.js:87 Error loading "firebase/angularfire" at http://localhost:8080/ng/firebase/angularfire.js
Error loading "firebase/angularfire" from "todo" at http://localhost:8080/todo.js
Not Found: http://localhost:8080/ng/firebase/angularfire.js

**Comment by vladima** [comment]
can you fix the casing of the matching entry for System.paths in index.html and check if it resolves the issue?

**Comment by sophiajt** [comment]
yup, working on a fix.  Checking in Linux now.

**Comment by MarkStega** [comment]
making the entire matching line lowercase allows the app to start; There are a couple of funky rendering issues in the app but at least it is running.

**Comment by MarkStega** [comment]
As an aside - the app starts in Chrome but not in Firefox or IE; I presume that this is an issue for the Angular team...

**Comment by sophiajt** [comment]
PR #16 should help with this... and yes, I think it does require Chrome for the time being.  Pinging @davideast

**Comment by sophiajt** [comment]
Merged.  Marking this as fixed.  May want to open another one about the Chrome-only support
