### ISSUE TITLE
I cannot get TypeScript 1.5 installed on my VS2013.

### ISSUE THREAD

**Issue by ghost** [Microsoft/ngconf2015demo#19]
I followed the instructions very carefully, but it seems to me that TypeScript 1.5 has not been installed on my Visual Studio 2013. I repeated several times and kept restarting, but there is no luck. I do have TypeScript 1.4 installed. I have Node.js and Visual Studio 2013 installed on Windows 8.1 x64. TypeScript 1.4 is just fine. Can anyone help?
![image 2](https://cloud.githubusercontent.com/assets/11084802/6702020/9afe4f68-cd5f-11e4-84e4-005ddf38c1fa.png)

**Comment by mhegazy** [comment]
What are the registry entries you have under: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0\TypeScriptLanguageService

specifically i am interested in the value of key CustomTypeScriptServicesFileLocation.

**Comment by ghost** [comment]
Please check the attached screenshot:
![image 3](https://cloud.githubusercontent.com/assets/11084802/6716483/d5294f36-cde0-11e4-98f7-b3140af1d028.png)

**Comment by mhegazy** [comment]
OK, one more attempt. can you delete the three entries.
- go to %ProgramFiles(x86)%\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript
- pack up the three files (lib.d.ts, lib.es6.d.ts, typescriptServices.js)
- copy the three files specified (lib.d.ts, lib.es6.d.ts, typescriptServices.js) from demo\tsc

And let me know what you see at then.

**Comment by vladima** [comment]
Can you tell what update of VS2013 do you have (check Help -> About Microsoft Visual Studio for this information) ?

**Comment by ghost** [comment]
@mhegazy Please check out this screenshot. I cannot find all of the files inside the TypeScript directory. There are some files missing, I am not sure it would work.
![image 4](https://cloud.githubusercontent.com/assets/11084802/6723091/b492e9b6-ce1d-11e4-8dfa-8bf3ec264a92.png)

@vladima I have attached the About screen for my VS 2013. Please check out.
![image 6](https://cloud.githubusercontent.com/assets/11084802/6723097/cddda7d0-ce1d-11e4-9cc8-e726d2748c94.png)

**Comment by mhegazy** [comment]
@rebeccapo i assume you have 1.4 installed (https://visualstudiogallery.msdn.microsoft.com/2d42d8dc-e085-45eb-a30b-3f7d50d55304)

can you 1. back up your typescriptServices.js and lib.d.ts and then copy in the ones in demo\tsc folder?

**Comment by ghost** [comment]
@mhegazy Thank you for your advice, so TypeScript 1.5 engine seems to be working, I still have the following error when I tried to run/build the solution. Kindly check the screenshot.

![image 1](https://cloud.githubusercontent.com/assets/11084802/6737678/18034ace-cea8-11e4-9d94-b53de631c518.png)

By the way, will I have to manually copy and paste the TypeScript files to get TypeScript 1.5 working?
Thank you.

**Comment by mhegazy** [comment]
The next time you install a TypeScript release it should put in the new version. if you want to revert to 1.4 behaviour, just put back your backed up files.

as for the --module issue, go to tools\options\Text Editor\TypeScript\Project, 
- Check "Automatically compile TypeScript files which are not part of a project", 
- this will enable the radio buttons underneath, select "use amd code generation"
- uncheck "Automatically compile TypeScript files which are not part of a project",

**Comment by vborovikov** [comment]
Check your PATH environment variable. It might contain paths to both v1.4 and v1.5.

**Comment by ghost** [comment]
@mhegazy I didn't work.

**Comment by mhegazy** [comment]
do you have a screen shot of your tools/options/Text Editor/TypeScript/Project ?

**Comment by josecasimiro** [comment]
FIXED

@rebeccapo Did you manage to solve the issue with the --module flag? The suggested fix by @mhegazy did not work for me either.

![image](https://cloud.githubusercontent.com/assets/807882/7566257/b0d6a606-f7ed-11e4-8468-a91c3d3bf1c8.png)

EDIT: Fixing my PATH env variable to the correct typescript folder fixed it for me, it was pointing to an older version.

**Comment by mhegazy** [comment]
@rebeccapo are you still running into this issue?

**Comment by vtkalek** [comment]
I have an issue with installation of typescript 1.5. 
It just not installing at all. I cant find any directory with typescript installed. And VS 2013 fire err message: Error 1   The specified task executable "tsc.exe" could not be run. Could not find a part of the path 'C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5'. PowerBIVisualsPlayground

I was trying to download 1.5 for VS2015 but the reference on site is redirecting me to https://www.visualstudio.com/downloads/download-visual-studio-vs .

That's just cool! :)

**Comment by mhegazy** [comment]
VS 2013 installer is at: https://visualstudiogallery.msdn.microsoft.com/b1fff87e-d68b-4266-8bba-46fad76bbf22
VS 2015 installer is at: https://www.visualstudio.com/downloads/download-visual-studio-vs (it is working fine for me. i would check firewall settings)

**Comment by rballonline** [comment]
Exact same issue, but with version 1.7.5.

**Comment by mhegazy** [comment]
This repo is deprecated. please refer to https://angular.io/docs/ts/latest/quickstart.html instead.

**Comment by jagadeeshpa** [comment]
Hi,
       please help me how to run typescript with protractor in eclipse neon

Thanks in advance
