### ISSUE TITLE
Why you use node instead of iis? Question

### ISSUE THREAD

**Issue by finfort** [Microsoft/ngconf2015demo#20]
I have read read this article "A Preview of Angular 2 and TypeScript in Visual Studio" and i wonder why at Microsoft you use node instead iis? Should i've use node also in production?

**Comment by sophiajt** [comment]
This demo should work across Windows, OS X, and Linux.  Because it's JavaScript-based, it's easier to get it up and running on Node.  It's also for demonstration purposes.

For your projects, you should choose what makes sense for your requirements.
