### ISSUE TITLE
Active and Completed Buttons not filtering

### ISSUE THREAD

**Issue by markuskremer** [Microsoft/ngconf2015demo#3]
Filtering(active, completed) not working

chome 41.0.2272.76 m

baa2d8d8f27798540f884f3cde5de2eaf1119618

**Comment by davideast** [comment]
This demo does not implement the filtering buttons. It was made to be easy to code in front of an audience. The best way to implement these actions would be with the router, which is not implemented yet. I think it would be best to revisit this once the router is ready.
