### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by Mig1st4ck** [Microsoft/ngconf2015demo#4]
Hi, i cloned this repo amd when i try to build like the line in:

```
node tsc\tsc.js -m amd todo.ts
```

I get this error.

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'd:\\ngconf2015demo\tsc\tsc.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

Is there any adicional step i missed?

**Comment by Mig1st4ck** [comment]
I found how to fix it.

```
node tsc/tsc.js -m amd todo.ts
```

Could you please change the documentation to reflect that so others don't have this problem.

**Comment by mhegazy** [comment]
thanks! readme updated.

**Comment by lukehoban** [comment]
Since you have a `tsconfig.json` in the root folder, don't you just need this?

``` bash
node tsc/tsc.js
```

**Comment by mhegazy** [comment]
Yup. Let me change that then.
