### ISSUE TITLE
Todo is not focused on double-click to edit

### ISSUE THREAD

**Issue by robertpenner** [Microsoft/ngconf2015demo#40]
## Expected

When a todo is double-clicked to edit, it should receive key events.
## Actual

The todo is not focused, so typing and Esc do not affect it.

**Comment by mhegazy** [comment]
This demo is intended to show case the basic integration of Angular2 and TypeScript, and not meant to be a fully functional todo mvc app. i am inclined to punt on this as it just a functional change in the app and does not show case new integration points.
