### ISSUE TITLE
Could not locate the TypeScript language service script at tsc\\typescriptServices.js

### ISSUE THREAD

**Issue by keelung** [Microsoft/ngconf2015demo#42]
after running vs\VSDevMode.ps1 -vsVersion 14 -tsScript tsc\

Could not locate the TypeScript language service script at tsc\typescriptServices.js
所在位置 D:\dev\GitHub\ngconf2015demo\vs\VSDevMode.ps1:45 字符: 9
-         Throw "Could not locate the TypeScript language service scrip ...
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (Could not locat...riptServices.js:String) [], RuntimeException
  - FullyQualifiedErrorId : Could not locate the TypeScript language service script at tsc\typescriptServices.js

**Comment by mhegazy** [comment]
can you try the full path instead:

> vs\VSDevMode.ps1 -vsVersion 14 -tsScript D:\dev\GitHub\ngconf2015demo\tsc\

**Comment by DeanB2015** [comment]
There's an updated version of VSDevMode.ps1 that I believe would fix this problem. https://github.com/Microsoft/TypeScript/blob/master/scripts/VSDevMode.ps1

**Comment by mhegazy** [comment]
Thanks @DeanB2015, ported in #43
