### ISSUE TITLE
VS 2015 RTM crash on opening ts file

### ISSUE THREAD

**Issue by ChrisTorng** [Microsoft/ngconf2015demo#44]
As https://github.com/Microsoft/TypeScript/issues/4011 mention, this demo makes VS 2015 RTM crash on opening ts file. You should provide updated information to the users of this demo. If not yet installed, then don't use the PS file to setup. If installed yet, then delete the three keys from regedit, before or after installing VS 2015 RTM.

**Comment by mhegazy** [comment]
thanks for the report. updated the steps.
