### ISSUE TITLE
[st3] Syntax highlighting is incorrect for interpolated strings

### ISSUE THREAD

**Issue by Taytay** [Microsoft/ngconf2015demo#6]
The syntax highlighting does not appear to recognize interpolated strings as strings.
Try pasting the below into your TS file:

``` Typescript
var str = `This throws the color off for the rest of the file: ', or until it gets to another apostrophe `);
var str2 = `In fact, the Github markdown has the same issue: ',now colors are back to normal. `);
```

On a related note: I'm excited to see such good TS editing in Sublime. I was just telling my team how good the intellisense is, the type inference, etc. Kudos.

**Comment by mhegazy** [comment]
Can you try again with https://github.com/Microsoft/ngconf2015demo/commit/8d053700b57262a87cc3d7c96387ef94ef27f795

**Comment by Taytay** [comment]
Um, that's insane. I went to create a PR for this, and saw your new commit. On a Saturday. Minutes after my report. 
Yep! That works very well. (Much better than my primitive attempt :) ) Thanks!
:+1:

**Comment by mhegazy** [comment]
Glad that helped :) have a good weekend!
