### ISSUE TITLE
Where will we find the Sublime-Plugin

### ISSUE THREAD

**Issue by manfredsteyer** [Microsoft/ngconf2015demo#8]
Hi,

during your session at ng-conf, you mentioned, that you are still working on the used typescript-plugin for sublime. Where will we find this plugin? What's the link of it's repository?

Wishes,
manfred

**Comment by Taytay** [comment]
@manfredsteyer, from one fellow user to another, for now you can find the plugin in this repository in the `sublimetext` folder. See the readme for install instructions.

I'll defer to the Typescript team on where this will live eventually. I presume they'll be extracting it into its own repo, putting it into Sublime's Package Control, etc.

**Comment by sophiajt** [comment]
What @Taytay said :)  We want to bake it a little longer first, as it's still pretty alpha.

**Comment by manfredsteyer** [comment]
ok, thx. Just want to make sure, that I find out, when it's finished. I've played around with the alpha that can be found in this repro. Great for learning Angular2+TypeScript!

**Comment by DanielRosenwasser** [comment]
You can get the bits from [here](https://github.com/Microsoft/TypeScript-Sublime-Plugin) but you should be able to install the ~~**TypeScriptLang**~~ **TypeScript** package in [Package Control](https://packagecontrol.io/) soon after it's officially accepted.
